sudo: required
services:
    - docker

before_install:
    - docker build -t ekarychkovsky/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ekarychkovsky/react-test npm test

after_success:
    - docker build -t ekarychkovsky/udemy-multi-client ./client
    - docker build -t ekarychkovsky/udemy-multi-nginx ./nginx
    - docker build -t ekarychkovsky/udemy-multi-server ./server
    - docker build -t ekarychkovsky/udemy-multi-worker ./worker
    # Login to Docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to Docker Hub
    - docker push ekarychkovsky/udemy-multi-client
    - docker push ekarychkovsky/udemy-multi-nginx
    - docker push ekarychkovsky/udemy-multi-server
    - docker push ekarychkovsky/udemy-multi-worker
